version: '2'
services:
  web:
    build:
      context: ./web
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    links:
      - api
  api:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8081:3000"